import 'package:flutter/material.dart';

void main() => runApp(const FinWiseApp());

class C {
  static const green = Color(0xFF00D09E);
  static const pale = Color(0xFFF1FFF7);
  static const soft = Color(0xFFDFF7E8);
  static const ink = Color(0xFF073B3A);
  static const blue = Color(0xFF2F80ED);
}

class FinWiseApp extends StatefulWidget { const FinWiseApp({super.key}); @override State<FinWiseApp> createState()=>_FinWiseAppState(); }
class _FinWiseAppState extends State<FinWiseApp>{
  bool dark=false;
  @override Widget build(BuildContext context)=>MaterialApp(
    debugShowCheckedModeBanner:false,
    title:'FinWise',
    themeMode:dark?ThemeMode.dark:ThemeMode.light,
    theme:ThemeData(useMaterial3:true, scaffoldBackgroundColor:C.green, fontFamily:'Arial', colorScheme:ColorScheme.fromSeed(seedColor:C.green, primary:C.green, surface:C.pale), textTheme:const TextTheme(bodyMedium:TextStyle(color:C.ink))),
    darkTheme:ThemeData(useMaterial3:true, brightness:Brightness.dark, scaffoldBackgroundColor:const Color(0xFF052F2E), colorScheme:ColorScheme.fromSeed(seedColor:C.green, brightness:Brightness.dark, primary:C.green, surface:const Color(0xFF073B3A))),
    home:LaunchPage(onDone:()=>Navigator.of(context).pushReplacement(MaterialPageRoute(builder:(_)=>Shell(onTheme:()=>setState(()=>dark=!dark))))),
  );
}

class LaunchPage extends StatelessWidget{
  final VoidCallback onDone; const LaunchPage({super.key,required this.onDone});
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Container(width:double.infinity,color:C.green,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[
    const Icon(Icons.stacked_line_chart_rounded,size:88,color:Colors.white),const SizedBox(height:10),const Text('FinWise',style:TextStyle(fontSize:34,fontWeight:FontWeight.w800,color:Colors.white)),const SizedBox(height:6),const Text('Finance made simple',style:TextStyle(color:Colors.white70,fontSize:15)),const SizedBox(height:60),
    FilledButton(style:FilledButton.styleFrom(backgroundColor:C.pale,foregroundColor:C.ink,padding:const EdgeInsets.symmetric(horizontal:56,vertical:16)),onPressed:onDone,child:const Text('Get Started',style:TextStyle(fontWeight:FontWeight.w700)))
  ]))));
}

class Shell extends StatefulWidget{final VoidCallback onTheme;const Shell({super.key,required this.onTheme});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int index=0; final pages=const [HomePage(),AnalysisPage(),TransactionsPage(),CategoriesPage(),ProfilePage()];
 @override Widget build(BuildContext context)=>Scaffold(body:pages[index],bottomNavigationBar:SafeArea(top:false,child:Container(margin:const EdgeInsets.fromLTRB(16,0,16,10),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(34)),child:NavigationBar(height:64,backgroundColor:Colors.transparent,indicatorColor:C.green,selectedIndex:index,labelBehavior:NavigationDestinationLabelBehavior.alwaysHide,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.analytics_outlined),label:'Analysis'),NavigationDestination(icon:Icon(Icons.swap_horiz_rounded),label:'Transactions'),NavigationDestination(icon:Icon(Icons.layers_outlined),label:'Categories'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')])))));
}

class Top extends StatelessWidget{final String title,sub;const Top(this.title,this.sub,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(22,18,22,18),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w800,color:C.ink)),Text(sub,style:const TextStyle(fontSize:12,color:C.ink))])),CircleAvatar(backgroundColor:C.pale,child:Icon(Icons.notifications_none_rounded,color:C.ink))]));}

class HomePage extends StatelessWidget{const HomePage({super.key});@override Widget build(BuildContext context)=>SafeArea(child:Column(children:[const Top('Hi, Welcome Back','Good Morning'),const Balance(),Expanded(child:Sheet(child:ListView(padding:const EdgeInsets.fromLTRB(20,22,20,30),children:[const QuickCard(),const SizedBox(height:18),const Segments(),const SizedBox(height:12),...sample.take(3).map((x)=>TxTile(x))])))]));}

class Balance extends StatelessWidget{const Balance({super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(24,4,24,22),child:Column(children:[const Row(children:[Expanded(child:Metric('▣ Total Balance','\$7,783.00',Colors.white)),SizedBox(height:44,child:VerticalDivider(color:Colors.white54)),Expanded(child:Metric('▣ Total Expense','-\$1,187.40',C.blue))]),const SizedBox(height:14),Container(height:18,decoration:BoxDecoration(color:C.pale,borderRadius:BorderRadius.circular(20)),child:Row(children:[Container(width:105,alignment:Alignment.center,decoration:BoxDecoration(color:C.ink,borderRadius:BorderRadius.circular(20)),child:const Text('30%',style:TextStyle(color:Colors.white,fontSize:10))),const Expanded(child:Center(child:Text('\$20,000.00',style:TextStyle(fontWeight:FontWeight.bold,fontSize:10,color:C.ink))))])),const SizedBox(height:10),const Align(alignment:Alignment.centerLeft,child:Text('☑  30% Of Your Expenses, Looks Good.',style:TextStyle(color:C.ink,fontSize:12,fontWeight:FontWeight.w600)))]));}
class Metric extends StatelessWidget{final String a,b;final Color color;const Metric(this.a,this.b,this.color,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(horizontal:10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:11,color:C.ink)),Text(b,style:TextStyle(fontSize:21,fontWeight:FontWeight.w800,color:color))]));}
class Sheet extends StatelessWidget{final Widget child;const Sheet({super.key,required this.child});@override Widget build(BuildContext c)=>Container(width:double.infinity,decoration:BoxDecoration(color:Theme.of(c).colorScheme.surface,borderRadius:const BorderRadius.vertical(top:Radius.circular(38))),child:child);}
class QuickCard extends StatelessWidget{const QuickCard({super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:C.green,borderRadius:BorderRadius.circular(22)),child:const Row(children:[Expanded(child:Column(children:[CircleAvatar(radius:27,backgroundColor:Colors.transparent,child:Icon(Icons.directions_car_outlined,size:36,color:C.ink)),Text('Savings\nOn Goals',textAlign:TextAlign.center,style:TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:C.ink))])),SizedBox(height:76,child:VerticalDivider(color:Colors.white)),Expanded(flex:2,child:Column(children:[Mini(Icons.layers_outlined,'Revenue Last Week','\$4,000.00',C.ink),Divider(color:Colors.white70),Mini(Icons.restaurant_outlined,'Food Last Week','-\$100.00',C.blue)]))]));}
class Mini extends StatelessWidget{final IconData i;final String a,b;final Color color;const Mini(this.i,this.a,this.b,this.color,{super.key});@override Widget build(BuildContext c)=>Row(children:[Icon(i,color:C.ink),const SizedBox(width:10),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:9,color:C.ink)),Text(b,style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:color))])]);}
class Segments extends StatelessWidget{const Segments({super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(4),decoration:BoxDecoration(color:C.soft,borderRadius:BorderRadius.circular(20)),child:Row(children:['Daily','Weekly','Monthly'].map((e)=>Expanded(child:Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:BoxDecoration(color:e=='Monthly'?C.green:Colors.transparent,borderRadius:BorderRadius.circular(18)),child:Text(e,textAlign:TextAlign.center,style:const TextStyle(color:C.ink,fontWeight:FontWeight.w600,fontSize:12))))).toList()));}

class Tx{final IconData icon;final String title,time,cat,amount;final Color color;const Tx(this.icon,this.title,this.time,this.cat,this.amount,this.color);}
const sample=[Tx(Icons.layers_outlined,'Salary','18:27 - April 30','Monthly','\$4,000.00',Color(0xFF70B7FF)),Tx(Icons.shopping_bag_outlined,'Groceries','17:00 - April 24','Pantry','-\$100.00',Color(0xFF3998FF)),Tx(Icons.handshake_outlined,'Rent','8:30 - April 15','Rent','-\$674.40',Color(0xFF1477F8)),Tx(Icons.directions_bus_outlined,'Transport','9:30 - April 08','Fuel','-\$4.13',Color(0xFF60A5FA)),Tx(Icons.restaurant_outlined,'Food','19:30 - March 31','Dinner','-\$70.40',Color(0xFF60A5FA))];
class TxTile extends StatelessWidget{final Tx x;const TxTile(this.x,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[CircleAvatar(backgroundColor:x.color,child:Icon(x.icon,color:Colors.white,size:21)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(x.title,style:const TextStyle(fontWeight:FontWeight.w700,color:C.ink)),Text(x.time,style:const TextStyle(fontSize:9,color:C.blue,fontWeight:FontWeight.w600))])),Container(width:1,height:30,color:C.green),const SizedBox(width:12),SizedBox(width:55,child:Text(x.cat,style:const TextStyle(fontSize:10,color:C.ink))),Container(width:1,height:30,color:C.green),const SizedBox(width:10),Text(x.amount,style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:x.amount.startsWith('-')?C.blue:C.ink))]));}

class TransactionsPage extends StatelessWidget{const TransactionsPage({super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[const Top('Transaction','Your activity'),const Balance(),Expanded(child:Sheet(child:ListView(padding:const EdgeInsets.all(20),children:[const Text('April',style:TextStyle(fontWeight:FontWeight.w800,fontSize:18,color:C.ink)),...sample.take(4).map((e)=>TxTile(e)),const SizedBox(height:10),const Text('March',style:TextStyle(fontWeight:FontWeight.w800,fontSize:18,color:C.ink)),TxTile(sample.last)]))) ]));}

class AnalysisPage extends StatelessWidget{const AnalysisPage({super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[const Top('Quickly Analysis','Monthly overview'),Expanded(child:Sheet(child:ListView(padding:const EdgeInsets.all(20),children:[const QuickCard(),const SizedBox(height:22),const Text('April Expenses',style:TextStyle(fontWeight:FontWeight.w800,fontSize:18,color:C.ink)),const SizedBox(height:12),Container(height:190,padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:C.pale,borderRadius:BorderRadius.circular(24)),child:const BarChart()),const SizedBox(height:18),...sample.take(3).map((e)=>TxTile(e))]))) ]));}
class BarChart extends StatelessWidget{const BarChart({super.key});@override Widget build(BuildContext c)=>Row(crossAxisAlignment:CrossAxisAlignment.end,mainAxisAlignment:MainAxisAlignment.spaceAround,children:[35,60,90,55,120,80,110,65].map((h)=>Container(width:12,height:h.toDouble(),decoration:BoxDecoration(color:h%2==0?C.green:C.blue,borderRadius:BorderRadius.circular(5)))).toList());}

class CategoriesPage extends StatelessWidget{const CategoriesPage({super.key});@override Widget build(BuildContext c){final cats=[(Icons.restaurant,'Food'),(Icons.shopping_bag,'Shopping'),(Icons.directions_car,'Transport'),(Icons.home,'Housing'),(Icons.favorite,'Health'),(Icons.movie,'Entertainment'),(Icons.school,'Education'),(Icons.more_horiz,'Others')];return SafeArea(child:Column(children:[const Top('Categories','Manage your spending'),Expanded(child:Sheet(child:GridView.count(crossAxisCount:2,padding:const EdgeInsets.all(22),mainAxisSpacing:14,crossAxisSpacing:14,children:cats.map((x)=>Container(decoration:BoxDecoration(color:C.soft,borderRadius:BorderRadius.circular(24)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[CircleAvatar(radius:28,backgroundColor:C.green,child:Icon(x.$1,color:C.ink)),const SizedBox(height:10),Text(x.$2,style:const TextStyle(fontWeight:FontWeight.w700,color:C.ink))])).toList()))) ]));}}

class ProfilePage extends StatelessWidget{const ProfilePage({super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[const Top('Profile','Account settings'),Expanded(child:Sheet(child:ListView(padding:const EdgeInsets.all(24),children:[const CircleAvatar(radius:44,backgroundColor:C.green,child:Icon(Icons.person,size:52,color:C.ink)),const SizedBox(height:12),const Center(child:Text('John Smith',style:TextStyle(fontWeight:FontWeight.w800,fontSize:20,color:C.ink))),const Center(child:Text('john@finwise.app',style:TextStyle(color:C.ink,fontSize:12))),const SizedBox(height:28),...[(Icons.person_outline,'Personal Information'),(Icons.lock_outline,'Security'),(Icons.notifications_none,'Notifications'),(Icons.help_outline,'Help & Support')].map((x)=>ListTile(leading:CircleAvatar(backgroundColor:C.soft,child:Icon(x.$1,color:C.ink)),title:Text(x.$2,style:const TextStyle(fontWeight:FontWeight.w600,color:C.ink)),trailing:const Icon(Icons.chevron_right,color:C.ink))),const SizedBox(height:14),OutlinedButton(onPressed:()=>Navigator.of(c).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>LaunchPage(onDone:()=>{})),(_)=>false),child:const Text('Log Out'))]))) ]));}
